port: 8080
database:
  host: primerbitcoin.sqlite
scheduler:
  schedule: "0 0 * * *"
notifications:
  telegram: true
order:
  decimals: 8
  side: buy
  quantity: 20
  minor: mxn
  major: btc
  symbol: BTCEUR
  book: btc_mxn
