port: 8080
database:
  host: primerbitcoin.sqlite
scheduler:
  schedule: "0 0 * * *"
metrics:
  interval: 30
notifications:
  telegram: true
order:
  decimals: 8
  side: buy
  amount: 10
  minor: mxn
  major: btc
  symbol: BTCEUR
  book: btc_mxn