name: Primerbitcoin CI

on: push
permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Calculate version
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: false
        DRY_RUN: true

    - name: Current Version
      run: |
        echo "${{ steps.taggerDryRun.outputs.tag }}"

    - name: New Version
      run: |
        echo "${{ steps.taggerDryRun.outputs.new_tag }}"

    - name: Increment type
      run: |
        echo "${{ steps.taggerDryRun.outputs.part }}"

    - name: Build
      run: APP_VERSION="${{ steps.taggerDryRun.outputs.new_tag }}" GOARCH=amd64 GOOS=linux go build -o build/primerbitcoin cmd/primerbitcoin/main.go

    - name: Persist Version as tag
      id: taggerFinal
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: false

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "build/primerbitcoin"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            sudo systemctl restart primerbitcoin
            sudo systemctl status primerbitcoin